# Generated by Django 5.2.13 on 2026-04-15 02:08

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
                ('provider', models.CharField(default='unknown', help_text='eks, aks, ovh, do, unknown', max_length=20)),
                ('environment', models.CharField(default='unknown', help_text='dev, staging, prod, unknown', max_length=20)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('project', models.CharField(blank=True, max_length=100)),
                ('k8s_version', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='CRD kind: ClusterComplianceReport, SbomReport', max_length=100)),
                ('source', models.CharField(default='trivy', max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_json', models.JSONField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_reports', to='core.cluster')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('cluster', 'Cluster'), ('ci', 'CI Pipeline')], default='cluster', max_length=10)),
                ('namespace', models.CharField(blank=True, max_length=253)),
                ('resource_kind', models.CharField(blank=True, max_length=100)),
                ('resource_name', models.CharField(blank=True, max_length=253)),
                ('title', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('vuln_id', models.CharField(blank=True, db_index=True, help_text='CVE ID, check ID, or rule ID', max_length=100)),
                ('category', models.CharField(choices=[('vulnerability', 'Vulnerability'), ('misconfiguration', 'Misconfiguration'), ('secret', 'Secret'), ('rbac', 'RBAC'), ('infra', 'Infrastructure'), ('policy', 'Policy')], max_length=30)),
                ('source', models.CharField(choices=[('trivy', 'Trivy'), ('kyverno', 'Kyverno')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('risk_accepted', 'Risk Accepted'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('hash_code', models.CharField(max_length=64)),
                ('epss_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('kev_listed', models.BooleanField(blank=True, null=True)),
                ('accepted_reason', models.TextField(blank=True)),
                ('accepted_until', models.DateField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='CRD-type-specific fields: description, remediation, score, component_name, installed_version, fixed_version, image, container, advisory_url, check_id, messages, etc.')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_findings', to=settings.AUTH_USER_MODEL)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.cluster')),
            ],
            options={
                'ordering': ['-first_seen'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['details'], name='finding_details_gin'), models.Index(fields=['cluster', 'source', 'status'], name='finding_cluster_source_status'), models.Index(fields=['severity', 'status'], name='finding_severity_status'), models.Index(fields=['last_seen'], name='finding_last_seen')],
                'constraints': [models.UniqueConstraint(fields=('origin', 'cluster', 'hash_code'), name='unique_finding_per_origin_cluster')],
            },
        ),
        migrations.CreateModel(
            name='ScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('trivy', 'Trivy'), ('kyverno', 'Kyverno')], max_length=30)),
                ('last_ingest', models.DateTimeField()),
                ('finding_count', models.IntegerField(default=0)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_statuses', to='core.cluster')),
            ],
            options={
                'verbose_name_plural': 'scan statuses',
                'constraints': [models.UniqueConstraint(fields=('cluster', 'source'), name='unique_scan_status_per_cluster_source')],
            },
        ),
    ]
