# Generated by Django 5.2.13 on 2026-04-26 01:44

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
                ('environment', models.CharField(choices=[('prod', 'Production'), ('staging', 'Staging'), ('dev', 'Development')], default='dev', help_text='dev / staging / prod — auto-detected from cluster name regex.', max_length=20)),
                ('environment_is_manual', models.BooleanField(default=False)),
                ('provider', models.CharField(default='onprem', help_text='aws / eks / gcp / gke / azure / aks / onprem — derived from node providerID.', max_length=20)),
                ('provider_is_manual', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, help_text='From topology.kubernetes.io/region on a worker node.', max_length=64)),
                ('region_is_manual', models.BooleanField(default=False)),
                ('k8s_version', models.CharField(blank=True, max_length=32)),
                ('consecutive_incomplete_inventories', models.PositiveIntegerField(default=0, help_text='Incremented by the inventory reap when complete_snapshot=true is absent for a cycle; reset to 0 on a complete reap. Threshold crossing emits reap.inventory.persistent_incomplete.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Bumped on every successful inventory sync.', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EpssScore',
            fields=[
                ('vuln_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('percentile', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', 'vuln_id'],
            },
        ),
        migrations.CreateModel(
            name='KevEntry',
            fields=[
                ('vuln_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('added_at', models.DateField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True)),
                ('required_action', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added_at', 'vuln_id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(help_text='sha256:... canonical identity.', max_length=80, unique=True)),
                ('ref', models.CharField(blank=True, help_text='Most-recently-seen full image reference, as received.', max_length=512)),
                ('registry', models.CharField(blank=True, max_length=253)),
                ('repository', models.CharField(blank=True, max_length=253)),
                ('os_family', models.CharField(blank=True, max_length=32)),
                ('os_version', models.CharField(blank=True, max_length=32)),
                ('base_eosl', models.BooleanField(default=False)),
                ('deployed', models.BooleanField(default=True, help_text='True iff observed as a running container image in any deployed Workload.')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ref'],
                'indexes': [models.Index(fields=['deployed'], name='image_deployed')],
            },
        ),
        migrations.CreateModel(
            name='IngestQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(help_text='String — matched against Cluster.name during dispatch.', max_length=253)),
                ('kind', models.CharField(max_length=64)),
                ('import_id', models.CharField(max_length=32)),
                ('raw_json', models.JSONField()),
                ('complete_snapshot', models.BooleanField(default=False, help_text='Set by the importer on the final inventory payload of a cycle.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['cluster_name', 'kind', 'import_id'], name='ingest_queue_tuple'), models.Index(fields=['status', 'created_at'], name='ingest_queue_status_created')],
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('annotations', models.JSONField(blank=True, default=dict)),
                ('internet_exposed', models.BooleanField(default=False, help_text='Rollup: any Workload in this namespace has publicly_exposed=true.')),
                ('exposure_is_manual', models.BooleanField(default=False)),
                ('contains_sensitive_data', models.BooleanField(default=False)),
                ('sensitive_is_manual', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='core.cluster')),
            ],
            options={
                'ordering': ['cluster_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VexStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(db_index=True, max_length=128)),
                ('image_digest', models.CharField(blank=True, help_text='Empty when the statement is vendor-wide.', max_length=80)),
                ('status', models.CharField(choices=[('affected', 'Affected'), ('not_affected', 'Not Affected'), ('fixed', 'Fixed'), ('under_investigation', 'Under Investigation')], max_length=32)),
                ('justification', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(blank=True, help_text='Document URL or path.', max_length=512)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['vuln_id', 'image_digest'], name='vex_lookup')],
                'constraints': [models.UniqueConstraint(fields=('vuln_id', 'image_digest', 'source'), name='unique_vex_statement')],
            },
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Deployment', 'Deployment'), ('StatefulSet', 'StatefulSet'), ('DaemonSet', 'DaemonSet'), ('CronJob', 'CronJob'), ('Job', 'Job'), ('Pod', 'Pod')], max_length=32)),
                ('name', models.CharField(max_length=253)),
                ('service_account', models.CharField(blank=True, default='default', max_length=253)),
                ('replicas', models.PositiveIntegerField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=dict, help_text='Pod template labels — used for Service / Ingress selector matching.')),
                ('publicly_exposed', models.BooleanField(default=False, help_text='Auto-derived: true iff backed by an external Ingress OR a non-internal LoadBalancer Service. Admin override via publicly_exposed_is_manual.')),
                ('publicly_exposed_is_manual', models.BooleanField(default=False)),
                ('deployed', models.BooleanField(default=True, help_text='Maintained by the inventory reap.')),
                ('last_inventory_at', models.DateTimeField(blank=True, help_text='Bumped only by inventory-kind handlers. Drives the deployed-flag diff (`deployed = last_inventory_at >= mark.started_at`). Scan handlers must not touch this field.', null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='Bumped on any touch (inventory or scan).')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='core.cluster')),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='core.namespace')),
            ],
            options={
                'ordering': ['cluster_id', 'namespace_id', 'kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_kind', models.CharField(choices=[('global', 'Global'), ('cluster', 'Cluster'), ('namespace', 'Namespace'), ('workload', 'Workload')], max_length=20)),
                ('severity_counts', models.JSONField(blank=True, default=dict, help_text='{critical: N, high: N, medium: N, low: N, info: N, unknown: N}')),
                ('priority_counts', models.JSONField(blank=True, default=dict, help_text='{immediate: N, out_of_cycle: N, scheduled: N, defer: N}')),
                ('total_active', models.PositiveIntegerField(default=0)),
                ('total_actioned', models.PositiveIntegerField(default=0)),
                ('import_id', models.CharField(blank=True, help_text='Import that produced this snapshot. Empty for safety-net rows.', max_length=32)),
                ('image_digest_set', models.JSONField(blank=True, default=list, help_text='Sorted array of digests across primary + init containers.')),
                ('image_set_changed_from_previous', models.BooleanField(default=False)),
                ('change_kind', models.CharField(choices=[('none', 'No change'), ('added', 'Added'), ('removed', 'Removed'), ('replaced', 'Replaced'), ('mixed', 'Mixed'), ('first_seen', 'First seen')], default='none', max_length=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.cluster')),
                ('namespace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.namespace')),
                ('workload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.workload')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanInconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('image_digest', models.CharField(blank=True, max_length=80)),
                ('seen_in_inventory', models.BooleanField(default=False)),
                ('seen_in_scans', models.BooleanField(default=False)),
                ('first_observed_at', models.DateTimeField(auto_now_add=True)),
                ('last_observed_at', models.DateTimeField(auto_now=True)),
                ('consecutive_cycles', models.PositiveIntegerField(default=1)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_inconsistencies', to='core.cluster')),
                ('workload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_inconsistencies', to='core.workload')),
            ],
            options={
                'ordering': ['-last_observed_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('trivy', 'Trivy'), ('kyverno', 'Kyverno'), ('kubepostureng-policy', 'KubePostureNG')], max_length=32)),
                ('category', models.CharField(choices=[('vulnerability', 'Vulnerability'), ('config', 'Configuration'), ('exposed-secret', 'Exposed Secret'), ('rbac', 'RBAC'), ('compliance', 'Compliance'), ('policy', 'Policy')], max_length=32)),
                ('vuln_id', models.CharField(blank=True, db_index=True, help_text='Source-defined identifier as opaque string — CVE-*, GHSA-*, vendor IDs, AVD-* or Kyverno policy names. EPSS / KEV joins match on the CVE-* prefix only.', max_length=128)),
                ('pkg_name', models.CharField(blank=True, db_index=True, max_length=256)),
                ('installed_version', models.CharField(blank=True, max_length=128)),
                ('fixed_version', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info'), ('unknown', 'Unknown')], max_length=16)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=128)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Source-specific fields not promoted to columns.')),
                ('effective_priority', models.CharField(choices=[('immediate', 'Immediate'), ('out_of_cycle', 'Out-of-Cycle'), ('scheduled', 'Scheduled'), ('defer', 'Defer')], db_index=True, default='scheduled', max_length=20)),
                ('epss_score', models.FloatField(blank=True, null=True)),
                ('epss_percentile', models.FloatField(blank=True, null=True)),
                ('kev_listed', models.BooleanField(default=False)),
                ('vex_status', models.CharField(blank=True, choices=[('affected', 'Affected'), ('not_affected', 'Not Affected'), ('fixed', 'Fixed'), ('under_investigation', 'Under Investigation')], default='', max_length=32)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash_code', models.CharField(help_text='sha256 of (source, category, vuln_id, workload.id or cluster.name, image.digest, pkg_name, installed_version).', max_length=64)),
                ('cluster', models.ForeignKey(help_text='Always set. For workload-scoped findings, redundant with workload.cluster — kept on the row for query convenience and for cluster-scoped findings (workload null).', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.cluster')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.image')),
                ('workload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.workload')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_kind', models.CharField(choices=[('ReplicaSet', 'ReplicaSet'), ('Job', 'Job')], max_length=32)),
                ('alias_name', models.CharField(max_length=253)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_aliases', to='core.cluster')),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_aliases', to='core.namespace')),
                ('target_workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.workload')),
            ],
            options={
                'ordering': ['cluster_id', 'namespace_id', 'alias_kind', 'alias_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadImageObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(help_text='Disambiguates multi-container Pods.', max_length=253)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.image')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_observations', to='core.workload')),
            ],
            options={
                'ordering': ['workload_id', 'container_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.CharField(help_text='Registry key from core.signals.SIGNALS.', max_length=128)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('currently_active', models.BooleanField(default=True, help_text='True iff the source still reports this signal at last reap. False after the reap observes silence.')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Source-specific context (e.g. capability name, CRB granting admin).')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.workload')),
            ],
            options={
                'ordering': ['workload_id', 'signal_id'],
            },
        ),
        migrations.CreateModel(
            name='FindingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('acknowledge', 'Acknowledge'), ('accept', 'Accept'), ('false_positive', 'False Positive'), ('scheduled', 'Scheduled')], max_length=20)),
                ('scope_kind', models.CharField(choices=[('per-finding', 'Per Finding'), ('per-vuln-image', 'Per (Vuln, Image)'), ('per-vuln', 'Per Vuln')], default='per-finding', max_length=20)),
                ('vuln_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, help_text='Required for action_type=accept; optional otherwise.', null=True)),
                ('ticket_ref', models.CharField(blank=True, max_length=128)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Non-null = no longer in effect; append a new row to revive.', null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_actions', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.finding')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finding_actions', to='core.image')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope_kind', 'vuln_id'], name='finding_action_vuln'), models.Index(fields=['scope_kind', 'image'], name='finding_action_image'), models.Index(fields=['finding', 'revoked_at'], name='finding_action_finding_revoked'), models.Index(fields=['expires_at'], name='finding_action_expires')],
            },
        ),
        migrations.CreateModel(
            name='ImportMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='inventory | trivy.VulnerabilityReport | trivy.ConfigAuditReport | trivy.ExposedSecretReport | trivy.RbacAssessmentReport | trivy.ClusterRbacAssessmentReport | trivy.InfraAssessmentReport | trivy.ClusterComplianceReport | kyverno.PolicyReport | kyverno.ClusterPolicyReport', max_length=64)),
                ('import_id', models.CharField(help_text='ULID generated by the importer at cycle start.', max_length=32)),
                ('state', models.CharField(choices=[('open', 'Open'), ('draining', 'Draining'), ('reaped', 'Reaped')], default='open', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('observed_count', models.IntegerField(blank=True, help_text='Set by /imports/finish/. Gates the zero-input no-op rule for scan kinds.', null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_marks', to='core.cluster')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['cluster', 'kind', 'state'], name='import_mark_state'), models.Index(fields=['state', 'started_at'], name='import_mark_safetynet')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'kind', 'import_id'), name='unique_import_mark')],
            },
        ),
        migrations.AddIndex(
            model_name='namespace',
            index=models.Index(fields=['cluster', 'active'], name='namespace_cluster_active'),
        ),
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='unique_namespace_per_cluster'),
        ),
        migrations.AddIndex(
            model_name='workload',
            index=models.Index(fields=['cluster', 'deployed'], name='workload_cluster_deployed'),
        ),
        migrations.AddIndex(
            model_name='workload',
            index=models.Index(fields=['cluster', 'publicly_exposed'], name='workload_cluster_exposed'),
        ),
        migrations.AddConstraint(
            model_name='workload',
            constraint=models.UniqueConstraint(fields=('cluster', 'namespace', 'kind', 'name'), name='unique_workload_identity'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['scope_kind', 'captured_at'], name='snapshot_scope_captured'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['workload', 'captured_at'], name='snapshot_workload'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['cluster', 'captured_at'], name='snapshot_cluster'),
        ),
        migrations.AddIndex(
            model_name='scaninconsistency',
            index=models.Index(fields=['cluster', 'kind'], name='scan_inconsist_ck'),
        ),
        migrations.AddIndex(
            model_name='scaninconsistency',
            index=models.Index(fields=['last_observed_at'], name='scan_inconsist_age'),
        ),
        migrations.AddConstraint(
            model_name='scaninconsistency',
            constraint=models.UniqueConstraint(fields=('cluster', 'kind', 'workload', 'image_digest'), name='unique_scan_inconsistency'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=django.contrib.postgres.indexes.GinIndex(fields=['details'], name='finding_details_gin'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['workload', 'effective_priority'], name='finding_workload_priority'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['cluster', 'effective_priority'], name='finding_cluster_priority'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['last_seen'], name='finding_last_seen'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['image'], name='finding_image'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('source', 'hash_code'), name='unique_finding_per_source_hash'),
        ),
        migrations.AddIndex(
            model_name='workloadalias',
            index=models.Index(fields=['cluster', 'alias_kind', 'alias_name'], name='workload_alias_lookup'),
        ),
        migrations.AddConstraint(
            model_name='workloadalias',
            constraint=models.UniqueConstraint(fields=('cluster', 'namespace', 'alias_kind', 'alias_name'), name='unique_workload_alias'),
        ),
        migrations.AddIndex(
            model_name='workloadimageobservation',
            index=models.Index(fields=['image'], name='wio_image'),
        ),
        migrations.AddConstraint(
            model_name='workloadimageobservation',
            constraint=models.UniqueConstraint(fields=('workload', 'image', 'container_name'), name='unique_workload_image_container'),
        ),
        migrations.AddIndex(
            model_name='workloadsignal',
            index=models.Index(fields=['workload', 'currently_active'], name='workload_signal_active'),
        ),
        migrations.AddIndex(
            model_name='workloadsignal',
            index=models.Index(fields=['signal_id'], name='workload_signal_id'),
        ),
        migrations.AddConstraint(
            model_name='workloadsignal',
            constraint=models.UniqueConstraint(fields=('workload', 'signal_id'), name='unique_workload_signal'),
        ),
    ]
