# Generated by Django 5.2.13 on 2026-05-05 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='reimport_requested_at',
            field=models.DateTimeField(blank=True, help_text="Set when an admin clicks 'Re-import'. The workload-cluster trigger CronJob polls /api/v1/imports/pending/ and runs a full import when this is non-NULL and no import is in flight. Cleared by /imports/pending/clear/ once an import that started after the request finishes.", null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reimport_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimport_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
