# Generated by Django 5.2.13 on 2026-05-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_cluster_reimport_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='source',
            field=models.CharField(choices=[('trivy', 'Trivy'), ('kyverno', 'Kyverno')], max_length=32),
        ),
    ]
