# Generated by Django 5.2.13 on 2026-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_cluster_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadimageobservation',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, help_text="Bumped on every inventory cycle that observes this (workload, image, container) combination. The inventory reap uses `last_seen_at >= mark.started_at` to decide which observations are 'current' for the deployed-flag diff. Older rows stay in the DB as history but no longer anchor `Image.deployed=true`."),
        ),
        migrations.AlterField(
            model_name='workloadalias',
            name='alias_kind',
            field=models.CharField(choices=[('ReplicaSet', 'ReplicaSet'), ('Job', 'Job'), ('Pod', 'Pod')], max_length=32),
        ),
    ]
