# Generated by Django 5.2.13 on 2026-04-15 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_finding_sql_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('total_controls', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='trivy', help_text='trivy (built-in spec) or custom (hand-authored YAML)', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('section', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('check_type', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual')], default='automated', max_length=20)),
                ('check_ids', models.JSONField(blank=True, default=list, help_text='List of Trivy AVD-* check IDs mapped to this control')),
                ('kyverno_policies', models.JSONField(blank=True, default=list, help_text='List of Kyverno policy names that enforce this control')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='core.framework')),
            ],
            options={
                'ordering': ['framework', 'control_id'],
                'unique_together': {('framework', 'control_id')},
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField()),
                ('total_pass', models.PositiveIntegerField(default=0)),
                ('total_fail', models.PositiveIntegerField(default=0)),
                ('total_manual', models.PositiveIntegerField(default=0)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, help_text='Pass percentage: total_pass / (total_pass + total_fail) * 100', max_digits=5)),
                ('raw_json', models.JSONField(blank=True, default=dict, help_text='Original ClusterComplianceReport for audit reference')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_snapshots', to='core.cluster')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.framework')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('MANUAL', 'Manual')], max_length=10)),
                ('total_pass', models.PositiveIntegerField(default=0)),
                ('total_fail', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.control')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.snapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['cluster', 'framework', '-scanned_at'], name='snapshot_cluster_fw_date'),
        ),
        migrations.AlterUniqueTogether(
            name='controlresult',
            unique_together={('snapshot', 'control')},
        ),
    ]
