# Generated by Django 5.2.13 on 2026-04-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_framework_control_snapshot_controlresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(blank=True, max_length=253)),
                ('resource_name', models.CharField(blank=True, max_length=253)),
                ('image', models.CharField(help_text='Full image reference (registry/repo:tag)', max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('library', 'Library'), ('framework', 'Framework'), ('os', 'OS Package'), ('container', 'Container'), ('application', 'Application'), ('other', 'Other')], default='library', max_length=30)),
                ('purl', models.CharField(blank=True, help_text='Package URL (pkg:deb/debian/openssl@1.1.1k)', max_length=1000)),
                ('licenses', models.JSONField(blank=True, default=list, help_text='List of SPDX license identifiers')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.cluster')),
            ],
            options={
                'ordering': ['name', 'version'],
                'indexes': [models.Index(fields=['name'], name='component_name'), models.Index(fields=['purl'], name='component_purl'), models.Index(fields=['cluster', 'image'], name='component_cluster_image')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'image', 'name', 'version'), name='unique_component_per_cluster_image')],
            },
        ),
    ]
