# Generated by Django 5.2.13 on 2026-05-22 03:58

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_finding_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbomComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purl', models.CharField(db_index=True, help_text='Canonical package URL, e.g. pkg:npm/lodash@4.17.21.', max_length=512)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('ecosystem', models.CharField(blank=True, db_index=True, help_text='npm, pypi, gomod, golang, cargo, deb, rpm, apk, maven, …', max_length=32)),
                ('component_type', models.CharField(blank=True, help_text='CycloneDX `type`: library, application, framework, …', max_length=32)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('layer_digest', models.CharField(blank=True, help_text='aquasecurity:trivy:LayerDigest property, if present.', max_length=80)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Full CycloneDX component object for future-proofing.')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(help_text='Lifecycle anchor. Cluster is derived via observations.', on_delete=django.db.models.deletion.CASCADE, related_name='sbom_components', to='core.image')),
            ],
            options={
                'ordering': ['name', 'version'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['raw'], name='sbomcomp_raw_gin'), models.Index(fields=['name', 'version'], name='sbomcomp_name_ver')],
                'constraints': [models.UniqueConstraint(fields=('image', 'purl'), name='unique_image_purl')],
            },
        ),
    ]
