# Generated by Django 5.2.13 on 2026-04-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_observation_last_seen'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='image_deployed',
        ),
        migrations.RemoveField(
            model_name='image',
            name='deployed',
        ),
    ]
