# Generated by Django 5.2.13 on 2026-04-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_image_image_deployed_remove_image_deployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='last_complete_inventory_at',
            field=models.DateTimeField(blank=True, help_text="`mark.started_at` of the most recent COMPLETE inventory cycle (carrying `complete_snapshot=true`). Anchor for `Image.objects.currently_running()`: an image observation is considered current iff its `last_seen_at` is at or after this timestamp. NULL until the first complete cycle reaps. Partial cycles do NOT advance this field — that's what protects partial imports from causing false negatives in image-deployment queries.", null=True),
        ),
    ]
