# Generated by Django 5.2.13 on 2026-04-15 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyComplianceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField()),
                ('total_pass', models.PositiveIntegerField(default=0)),
                ('total_fail', models.PositiveIntegerField(default=0)),
                ('total_warn', models.PositiveIntegerField(default=0)),
                ('total_skip', models.PositiveIntegerField(default=0)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, help_text='Pass percentage: total_pass / (total_pass + total_fail) * 100', max_digits=5)),
                ('raw_json', models.JSONField(blank=True, default=dict, help_text='Summary of ingested PolicyReport data')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_compliance_snapshots', to='core.cluster')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['cluster', '-scanned_at'], name='polsnap_cluster_date')],
            },
        ),
    ]
