# Generated by Django 5.2.13 on 2026-05-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_sbom_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFetchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_key', models.CharField(max_length=128, unique=True)),
                ('etag', models.CharField(blank=True, max_length=256)),
                ('last_modified', models.CharField(blank=True, help_text='HTTP Last-Modified header value (RFC 7231 date string).', max_length=64)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='finding',
            name='category',
            field=models.CharField(choices=[('vulnerability', 'Vulnerability'), ('config', 'Configuration'), ('exposed-secret', 'Exposed Secret'), ('rbac', 'RBAC'), ('compliance', 'Compliance'), ('policy', 'Policy'), ('supply_chain', 'Supply Chain')], max_length=32),
        ),
        migrations.AlterField(
            model_name='finding',
            name='source',
            field=models.CharField(choices=[('trivy', 'Trivy'), ('kyverno', 'Kyverno'), ('supply_chain_ioc', 'Supply-Chain IoC')], max_length=32),
        ),
        migrations.CreateModel(
            name='SupplyChainIoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purl', models.CharField(db_index=True, max_length=512)),
                ('feed_source', models.CharField(help_text='Feed identifier — currently "osv" or "aikido".', max_length=32)),
                ('advisory_id', models.CharField(help_text='Feed-native ID: GHSA-xxxx, MAL-xxxx, AIKIDO-xxxx, etc.', max_length=128)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('advisory_url', models.URLField(blank=True, max_length=512)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['purl'], name='scioc_purl'), models.Index(fields=['feed_source'], name='scioc_feed_source')],
                'constraints': [models.UniqueConstraint(fields=('feed_source', 'advisory_id', 'purl'), name='unique_feed_advisory_purl')],
            },
        ),
    ]
