# Generated by Django 5.2.13 on 2026-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_normalize_stored_purls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainioc',
            name='advisory_id',
            field=models.CharField(help_text='Feed-native ID: GHSA-xxxx, MAL-xxxx, etc.', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplychainioc',
            name='feed_source',
            field=models.CharField(help_text='Feed identifier — currently "osv".', max_length=32),
        ),
    ]
