# Generated by Django 5.2.13 on 2026-04-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_findinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='contains_sensitive_data',
            field=models.BooleanField(default=False, help_text='Cluster processes PII, financial, or regulated data'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='internet_exposed',
            field=models.BooleanField(default=False, help_text='Cluster has internet-facing services (ingress, LoadBalancer)'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='namespace_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-namespace exposure overrides. Inherits cluster defaults if not set. Format: {"namespace": {"internet_exposed": bool, "contains_sensitive_data": bool}}'),
        ),
        migrations.AddField(
            model_name='finding',
            name='effective_priority',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('out_of_cycle', 'Out-of-Cycle'), ('scheduled', 'Scheduled'), ('defer', 'Defer')], db_index=True, default='scheduled', help_text='Contextual priority from severity + EPSS/KEV + cluster/namespace exposure', max_length=20),
        ),
    ]
