# Generated by Django 5.2.17 on 2026-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_supplychainioc_advisory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestqueue',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text="Set when a worker flips this row to 'processing'. Lets reclaim_stale() detect items abandoned by a worker Job killed mid-item (e.g. activeDeadlineSeconds) — claim_batch only ever selects 'pending' rows, so without this a stuck 'processing' row (and its ImportMark's reap) would block forever.", null=True),
        ),
        migrations.AddIndex(
            model_name='ingestqueue',
            index=models.Index(fields=['status', 'claimed_at'], name='ingest_queue_status_claimed'),
        ),
    ]
