# Generated by Django 5.2.13 on 2026-04-28 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_drop_vex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingesttoken',
            name='name',
            field=models.CharField(help_text="Human-readable identifier (e.g., 'my-laptop', 'ci-bot').", max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_help', models.BooleanField(default=False, help_text='When True, `{% help %}…{% endhelp %}` blocks render as empty. Toggled from /profile/. See Architecture/dev_docs/08-ui.md §Help blocks.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kv_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
