# Generated by Django 5.2.13 on 2026-04-29 05:29

from django.db import migrations, models
from django.db.models import F


def backfill_currently_deployed(apps, schema_editor):
    """Seed currently_deployed for existing rows using the old query's
    semantics: a row is "deployed" iff its workload is deployed AND
    last_seen_at is at least cluster.last_complete_inventory_at.
    """
    Observation = apps.get_model("core", "WorkloadImageObservation")
    Observation.objects.filter(
        workload__deployed=True,
        last_seen_at__gte=F("workload__cluster__last_complete_inventory_at"),
    ).update(currently_deployed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ingesttoken_name_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadimageobservation',
            name='currently_deployed',
            field=models.BooleanField(db_index=True, default=False, help_text='True iff this (workload, image, container) was observed in the most recent COMPLETE inventory cycle. Set by the inventory reaper (core.services.reaper). Mirrors Workload.deployed. Default False because new rows are created mid-cycle and only the reaper has authority to mark them deployed at end of a complete cycle.'),
        ),
        migrations.AddField(
            model_name='workloadimageobservation',
            name='init_container',
            field=models.BooleanField(default=False, help_text='True if the container came from pod.spec.initContainers.'),
        ),
        migrations.AlterField(
            model_name='workloadimageobservation',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, help_text='Bumped by the parser on every cycle that re-observes this (workload, image, container) combination. Reaper diffs against ImportMark.started_at to flip currently_deployed.'),
        ),
        migrations.RunPython(
            backfill_currently_deployed,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
