# Generated by Django 5.2.17 on 2026-08-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ingestqueue_claimed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='first_seen_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Set once, at row creation. If a workload with this exact identity (cluster, namespace, kind, name) is deleted and later recreated, `unique_workload_identity` means the persist pass reuses this same row rather than creating a new one — so first_seen_at, WorkloadSignal history, and Snapshot history all carry over across the gap. This is intentional: the same workload identity can legitimately be redeployed (e.g. a deliberate recreate for some operational reason), and doing so should not reset what's already known about it. There is no generation/incarnation tracking to distinguish 'the same workload, redeployed' from 'a coincidentally same-named, unrelated workload' — by design, not an oversight."),
        ),
    ]
