# Generated by Django 5.2.13 on 2026-04-16 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_update_sql_views_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['cluster', 'status'], name='finding_cluster_status'),
        ),
    ]
