# Generated by Django 5.2.13 on 2026-04-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_recreate_sql_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='active',
            field=models.BooleanField(default=True, help_text='False when the namespace no longer appears in a complete cluster snapshot. Inactive namespaces are excluded from exposure rollups; their active/acknowledged findings are auto-resolved. Flipped back to True if the namespace reappears.'),
        ),
        migrations.AddField(
            model_name='namespace',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of most recent deactivation. Null while active.', null=True),
        ),
        migrations.AddIndex(
            model_name='namespace',
            index=models.Index(fields=['cluster', 'active'], name='namespace_cluster_active'),
        ),
    ]
