# Generated by Django 5.2.13 on 2026-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_recreate_views_with_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='network_policy_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of NetworkPolicy resources in this namespace at the last sync. Zero indicates no network segmentation — a finding here has a wider blast radius.'),
        ),
    ]
