"""ImportMark — kind-discriminated tracking of one (cluster, kind, import_id) cycle.

The importer generates a ULID `import_id` at cycle start and stamps it
on every payload. One ImportMark row exists per `(cluster, kind,
import_id)`; the kind discriminator dispatches the reap behaviour.

Lifecycle:
  open      — created by /imports/start/. Worker MAY NOT process queue
              items for this tuple yet.
  draining  — set by /imports/finish/. Worker may now claim items.
              Reap fires once the queue for this tuple is empty.
  reaped    — set by reap commit. Row is preserved as a per-cycle
              audit trail (not deleted).

`observed_count` is set by /imports/finish/ — the count of distinct
payloads the importer sent for this kind. The reap consults it for
the universal zero-input no-op rule (see dev_docs/11-import-robustness.md).
"""
from django.db import models
from django.utils import timezone

from core.constants import ImportMarkState


class ImportMark(models.Model):
    cluster = models.ForeignKey(
        "core.Cluster",
        on_delete=models.CASCADE,
        related_name="import_marks",
    )
    kind = models.CharField(
        max_length=64,
        help_text=(
            "inventory | trivy.VulnerabilityReport | trivy.ConfigAuditReport | "
            "trivy.ExposedSecretReport | trivy.RbacAssessmentReport | "
            "trivy.ClusterRbacAssessmentReport | trivy.InfraAssessmentReport | "
            "trivy.ClusterComplianceReport | kyverno.PolicyReport | "
            "kyverno.ClusterPolicyReport"
        ),
    )
    import_id = models.CharField(
        max_length=32,
        help_text="ULID generated by the importer at cycle start.",
    )

    state = models.CharField(
        max_length=16,
        choices=ImportMarkState.choices,
        default=ImportMarkState.OPEN,
    )

    started_at = models.DateTimeField()
    completed_at = models.DateTimeField(null=True, blank=True)
    observed_count = models.IntegerField(
        null=True,
        blank=True,
        help_text="Set by /imports/finish/. Gates the zero-input no-op rule for scan kinds.",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["cluster", "kind", "import_id"],
                name="unique_import_mark",
            ),
        ]
        indexes = [
            models.Index(fields=["cluster", "kind", "state"], name="import_mark_state"),
            models.Index(fields=["state", "started_at"], name="import_mark_safetynet"),
        ]
        ordering = ["-started_at"]

    def __str__(self) -> str:
        return f"{self.cluster.name}/{self.kind}/{self.import_id} [{self.state}]"

    @classmethod
    def open(cls, *, cluster, kind: str, import_id: str) -> tuple["ImportMark", bool]:
        """Idempotently open a mark for `(cluster, kind, import_id)`.

        Resets state to `open` and clears completed_at / observed_count
        so a retry of the same `import_id` starts clean.
        """
        return cls.objects.update_or_create(
            cluster=cluster,
            kind=kind,
            import_id=import_id,
            defaults={
                "state": ImportMarkState.OPEN.value,
                "started_at": timezone.now(),
                "completed_at": None,
                "observed_count": None,
            },
        )
